### ISSUE TITLE
Code Not working on stm32f4discovery board

### ISSUE THREAD

**Issue by KamranArain** [x893/Codec2WalkieTalkie#1]
after adding codec2 in code I uploaded the code but it isn't worked in loopback mode but when I debug that the code was stuck in HardFaultHandler and non of the led glow and I think it was due to external clock selection so I set it to 8Mhz but it also stuck again while initializing pins like PinMode() ftn I also changed .s and .c file of startup but still nothing worked

**Comment by x893** [comment]
i have not STM32F4Disco disco and can not check.

**Comment by Ultra-Challenger** [comment]
> i have not STM32F4Disco disco and can not check.

Did you have the STM32FDisco when you code? And have you tested the validity of the code？

**Comment by Ultra-Challenger** [comment]
> i have not STM32F4Disco disco and can not check.

Did you have the STM32FDisco when you code? And have you tested the validity of the code？

**Comment by KamranArain** [comment]
> > i have not STM32F4Disco disco and can not check.
> 
> Did you have the STM32FDisco when you code? And have you tested the validity of the code？

I have STM32F4 Disco board which has a mems microphone and audio output 3.5mm jack but for some reason this code isn't working.
I also tried to debug it but it was not debug able at that moment

**Comment by Ultra-Challenger** [comment]
> 

OK. Thank you.

**Comment by Ultra-Challenger** [comment]
> I have STM32F4 Disco board which has a mems microphone and audio output 3.5mm jack but for some reason this code isn't working. I also tried to debug it but it was not debug able at that moment

Thank you!
